---
apiVersion: k3d.io/v1alpha4
kind: Cluster
metadata:
  name: homelab
servers: 1
agents: 1
image: docker.io/rancher/k3s:v1.28.6-k3s1
ports:
  - port: 80:80
    nodeFilters:
      - loadbalancer
  - port: 443:443
    nodeFilters:
      - loadbalancer
  - port: 6443:6443
    nodeFilters:
      - server:*
# k3d-default registry is enabled for future workload deployments
registries:
  use:
    - k3d-default
